### ISSUE TITLE
Can't download data

### ISSUE THREAD

**Issue by aro-n** [podaac/data-subscriber#122]
I'm trying to download data from SMAP, made the installation of podaac-data-subscriber and configure netrc.

podaac-data-subscriber -c SMAP_RSS_L2_SSS_V4 -d ./data/SMAP_RSS_L2_SSS_V4 --start-date 2015-04-01T00:43:12Z 
[2023-03-07 14:09:19,991] {podaac_data_subscriber.py:335} DEBUG - Log level set to DEBUG
[2023-03-07 14:09:19,993] {podaac_data_subscriber.py:340} ERROR - Uncaught exception occurred during execution.
Traceback (most recent call last):
  File "/home/arofcn/anaconda3/lib/python3.8/site-packages/subscriber/podaac_data_subscriber.py", line 338, in main
    run()
  File "/home/arofcn/anaconda3/lib/python3.8/site-packages/subscriber/podaac_data_subscriber.py", line 124, in run
    pa.setup_earthdata_login_auth(edl)
  File "/home/arofcn/anaconda3/lib/python3.8/site-packages/subscriber/podaac_access.py", line 77, in setup_earthdata_login_auth
    username, _, password = netrc.netrc().authenticators(endpoint)
  File "/home/arofcn/anaconda3/lib/python3.8/netrc.py", line 30, in __init__
    self._parse(file, fp, default_netrc)
  File "/home/arofcn/anaconda3/lib/python3.8/netrc.py", line 104, in _parse
    raise NetrcParseError(
netrc.NetrcParseError: ~/.netrc access too permissive: access permissions must restrict access to only the owner (/home/arofcn/.netrc, line 3)

**Comment by aro-n** [comment]
this helped
chmod u+rw,u-x,go-rwx ~/.netrc
ls -la ~/.netrc

**Comment by mike-gangl** [comment]
thanks for the info- we can add that to any netrc documentation we have, but it is system specific (linux/unix/mac vs windows).

**Comment by aro-n** [comment]
linux debian 10
