### ISSUE TITLE
not-intuitive syntax with REQUIRED arguments

### ISSUE THREAD

**Issue by ifenty** [podaac/data-subscriber#38]
I use python, I use the command line.  installed data-subscriber. ran podaac-data-subscriber -h, quickly read the syntax, tried to download a single ECCO dataset into the current directory ``` -d ./```  Note, ```./``` is a perfectly normal syntax meaning current directory.  Error message is not helpful.
```
$ podaac-data-subscriber -c ECCO_L4_ATM_STATE_05DEG_DAILY_V4R4 -ed 1993-01-01 -d .
```

```
$ podaac-data-subscriber -c ECCO_L4_ATM_STATE_05DEG_DAILY_V4R4 -ed 1993-01-01T00:00:00Z -d ./
WARN: No .update in the data directory. (Is this the first run?)
Traceback (most recent call last):
  File "/home/ifenty/anaconda3/envs/ecco/bin/podaac-data-subscriber", line 8, in <module>
    sys.exit(run())
  File "/home/ifenty/anaconda3/envs/ecco/lib/python3.8/site-packages/subscriber/podaac_data_subscriber.py", line 345, in run
    with urlopen(url) as f:
  File "/home/ifenty/anaconda3/envs/ecco/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/ifenty/anaconda3/envs/ecco/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/ifenty/anaconda3/envs/ecco/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/home/ifenty/anaconda3/envs/ecco/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/home/ifenty/anaconda3/envs/ecco/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/home/ifenty/anaconda3/envs/ecco/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request
```

Took a while to discover that I need to specify ```-d DIRECTORY_NAME```  and that the DIRECTORY_NAME will be created.

**Comment by mike-gangl** [comment]
we might call this a bug. if a user uses the same directory (-d) for multiple collections, then there is no ability for it to know which collection the ".update" file belongs to. We should probably update this to use the collection name instead of the ".update" file name to ensure the same directory specified doesn't break functionality.

**Comment by ifenty** [comment]
I think it is a good idea to have the file be called collection_name.update or .collection_name_update or .update_collection_name.

I also think allowing `.` as a destination directory also makes sense.

**Comment by mike-gangl** [comment]
so if i'm not mistaken, you can use the `./` or `.` as a directory name:

podaac-data-subscriber -c ECCO_L4_ATM_STATE_05DEG_DAILY_V4R4 -ed 1993-01-01T00:00:00Z  -sd 1992-01-01T00:00:00Z -d .

The issue you are running into is a bug with the "missing" -sd entry. your command SHOULD work, but it doesn't due to some other checks that will be fixed, but wanted to let you know that the directory can be a `.` or a `./`
