### ISSUE TITLE
v1.9.0 fails because of missing dependency

### ISSUE THREAD

**Issue by frankinspace** [podaac/data-subscriber#72]
Installed version 1.9.0 with pip but it did not install the required tenacity dependency.

```
pip install --force --user -U podaac-data-subscriber
Collecting podaac-data-subscriber
  Using cached podaac_data_subscriber-1.9.0-py3-none-any.whl (22 kB)
Installing collected packages: podaac-data-subscriber
  Attempting uninstall: podaac-data-subscriber
    Found existing installation: podaac-data-subscriber 1.9.0
    Uninstalling podaac-data-subscriber-1.9.0:
      Successfully uninstalled podaac-data-subscriber-1.9.0
Successfully installed podaac-data-subscriber-1.9.0
```

If I try to run the new version:

```
Traceback (most recent call last):
  File "/home/DEV-cloud/.local/bin/podaac-data-subscriber", line 5, in <module>
    from subscriber.podaac_data_subscriber import main
  File "/home/DEV-cloud/.local/lib/python3.6/site-packages/subscriber/podaac_data_subscriber.py", line 25, in <module>
    from subscriber import podaac_access as pa
  File "/home/DEV-cloud/.local/lib/python3.6/site-packages/subscriber/podaac_access.py", line 21, in <module>
    import tenacity
ModuleNotFoundError: No module named 'tenacity'
Traceback (most recent call last):
  File "/home/DEV-cloud/.local/bin/podaac-data-subscriber", line 5, in <module>
    from subscriber.podaac_data_subscriber import main
  File "/home/DEV-cloud/.local/lib/python3.6/site-packages/subscriber/podaac_data_subscriber.py", line 25, in <module>
    from subscriber import podaac_access as pa
  File "/home/DEV-cloud/.local/lib/python3.6/site-packages/subscriber/podaac_access.py", line 21, in <module>
    import tenacity
ModuleNotFoundError: No module named 'tenacity'
```

**Comment by mike-gangl** [comment]
fixed in 1.10.0
